FROM jboss/keycloak:12.0.1

RUN mkdir -p /opt/jboss/keycloak/providers
ADD target/keycloak-userstorage-external-user-migration.jar /opt/jboss/keycloak/providers/keycloak-userstorage-external-user-migration.jar
